spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adoptpet_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: adoptmate
    password: adoptmate
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379
      # password: your_redis_password (필요 시 주석 해제)

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    serialization:
      fail-on-empty-beans: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: luo199829@gmail.com
    password: hsgl yoex mhfa ltzm
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

server:
  port: 8000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  expiration: 20000         # Access Token 유효 시간 (분)
  secretKey: b9a26eb960aa4b5269c7101d7c142fdc18ca5987b1697f477ed8fded5e7935aa51d7b563a477a352d079c14f031962056a5bcd4b12f3371ad2fcecfeb5f62550

  expirationRt: 120         # Refresh Token 유효 시간 (분)
  secretKeyRt: b9a26eb960aa4b5269c7101d7c142fdc18ca5987b1697f477ed8fded5e7935aa51d7b563a477a352d079c14f031962056a5bcd4b12f3371ad2fcecfeb5f62550
oauth2:
  kakao:
    client-id: 16a5cc3c2d930524373be21f6bf96353
    redirect-uri: http://localhost:8000/adoptmate/kakao